### ISSUE TITLE
Python tests do not run on all supported python versions

### ISSUE THREAD

**Issue by thedrow** [ohmu/omcache#18]
[tox](https://pypi.python.org/pypi/tox) can help with that.

**Comment by saaros** [comment]
Travis now runs the tests with all supported versions, see 1814102298c73c0c5495045975d579b6dec88b22 for Travis configuration and d194f2850dabbfedb7beec215b9a898c8dd5872a for the required changes for Python 3.

**Comment by thedrow** [comment]
:+1:
