### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by thedrow** [ohmu/omcache#22]
There is only one commit between the latest release and now.
Have you guys stopped maintaining the project?
There's still a lot of work to be done in terms of documentation and performance benchmarks.

**Comment by saaros** [comment]
The project is maintained, but it is not actively developed at the moment as we don't currently have need for new features in it and it works well as-is in our use cases.  Documentation could certainly be improved, but I don't think I'll do anything about it until I need more changes to the project.

I'm happy to review and help with documentation and other changes if someone else creates a pull request.

**Comment by thedrow** [comment]
Thanks for the heads up.
