### ISSUE TITLE
Documentation generation

### ISSUE THREAD

**Issue by saaros** [ohmu/omcache#6]
Add a Makefile target to create HTML and manpage documentation for the API.

**Comment by thedrow** [comment]
I'm really interested in this project but I can't use it as it is.
It really needs documentation to move forward.

**Comment by saaros** [comment]
The C API is documented in omcache_cdef.h but the Python API is still lacking documentation.  It's pretty straightforward, though, and the API implemented by omcache_pylibmc.py matches what pylibmc implements and documents so you could use it as a starting point.  I'll try to write some docs for the Python API and add some example uses of the APIs sometime soon.  You can also look at the unit tests and how they utilize the c and python apis.

**Comment by thedrow** [comment]
The problem is that the omcache_pylibmc is an experimental and just for demonstration.
I can't really use it.

**Comment by saaros** [comment]
Documentation is now autogenerated for the C API and published in http://omcache.readthedocs.org/ - will create a new ticket about documenting the Python api.

**Comment by thedrow** [comment]
Thank you!
